name: Android APK Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Projeyi indir
      uses: actions/checkout@v4

    - name: Java kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Gradle ile APK oluştur
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: APK'yı yükle
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
