name: Android APK Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Projeyi indir
      uses: actions/checkout@v4

    - name: Java Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: APK Derle
      run: |
        # settings.gradle dosyasının bulunduğu yeri bulalım
        PROJECT_DIR=$(find . -name "settings.gradle" -exec dirname {} \;)
        echo "Proje dizini bulundu: $PROJECT_DIR"
        cd "$PROJECT_DIR"

        if [ ! -f gradlew ]; then
          gradle wrapper
        fi
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: APK'yi Yukle
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: '**/app/build/outputs/apk/debug/app-debug.apk'
